# Run ./clone.sh first so ./quarkus-test exists, then: docker compose up --build
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: leopold
      POSTGRES_PASSWORD: bloom
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leopold -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./quarkus-test 
      dockerfile: ../Dockerfile  # Dockerfile is one level up in orchastrator root (or can keep inside service conetxt repo ./Dockerfile
    volumes:
      - ./quarkus-test/src:/app/src
      - ./quarkus-test/pom.xml:/app/pom.xml:ro
    environment:
      QUARKUS_PROFILE: dev
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/mydatabase
      QUARKUS_DATASOURCE_USERNAME: leopold
      QUARKUS_DATASOURCE_PASSWORD: bloom
    depends_on:
      postgres:
        condition: service_healthy
