services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: leopold
      POSTGRES_PASSWORD: bloom
      POSTGRES_DB: mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leopold -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend-angular-test #dir name of repo cloned from clone.sh
      dockerfile: ../Dockerfile.frontend #location of docker file relative to context path, can keep inside cloned repository (./Dockerfile) or inside orchestrator as in this example
    volumes:
      - ./frontend-angular-test/src:/app/src #parent dir name same as in context
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./quarkus-test #dir name of repo cloned from clone.sh
      dockerfile: ../Dockerfile.backend #location of docker file relative to context path, can keep inside cloned repository (./Dockerfile) or inside orchestrator as in this example
    volumes:
      - ./quarkus-test/src:/app/src #parent dir name same as in context
      - ./quarkus-test/pom.xml:/app/pom.xml:ro #parent dir name same as in context
    environment:
      QUARKUS_PROFILE: dev
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/mydatabase
      QUARKUS_DATASOURCE_USERNAME: leopold
      QUARKUS_DATASOURCE_PASSWORD: bloom
    depends_on:
      postgres:
        condition: service_healthy